{% set name = "fonttools" %}
{% set version = "3.26.0" %}
{% set sha256 = "a395b91f6c0bb2ee1ec0585fbb5c7117627c3c2baefbfef19b1194ca41fb2817" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/{{ name }}/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - brotli
    - unicodedata2
    - munkres

test:
  imports:
    - fontTools
    - fontTools.ttLib


about:
  home: https://github.com/fonttools/fonttools
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'fontTools is a library for manipulating fonts, written in Python.'

  description: |
    fontTools is a library for manipulating fonts, written in Python. The
    project includes the TTX tool, that can convert TrueType and OpenType
    fonts to and from an XML text format, which is also called TTX. It
    supports TrueType, OpenType, AFM and to an extent Type 1 and some
    Mac-specific formats. The project has a BSD-style open-source licence.

  doc_url: https://groups.google.com/forum/#!forum/fonttools
  dev_url: https://github.com/fonttools/fonttools

extra:
  recipe-maintainers:
    - CJ-Wright
