{% set name = "fonttools" %}
{% set version = "4.10.2" %}
{% set sha256 = "2ae6568736f1f280ffa7e2ea44e129c3304e9a7d9fe33ffabb165d36b136f5da" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.zip
  url: https://github.com/{{ name }}/{{ name }}/releases/download/{{ version }}/{{ name }}-{{ version }}.zip
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - fonttools = fontTools.__main__:main
    - ttx = fontTools.ttx:main
    - pyftsubset = fontTools.subset:main
    - pyftmerge = fontTools.merge:main
    - pyftinspect = fontTools.inspect:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - brotli
    - unicodedata2 >=12.1.0
    - munkres

test:
  imports:
    - fontTools
    - fontTools.ttLib
  commands:
    - fonttools subset --help
    - ttx -h
    - pyftsubset --help
    # pyftmerge has no help option
    # pyftinspect requires gtk

about:
  home: https://github.com/fonttools/fonttools
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: fontTools is a library for manipulating fonts, written in Python.

  description: |
    fontTools is a library for manipulating fonts, written in Python. The
    project includes the TTX tool, that can convert TrueType and OpenType
    fonts to and from an XML text format, which is also called TTX. It
    supports TrueType, OpenType, AFM and to an extent Type 1 and some
    Mac-specific formats. The project has a BSD-style open-source licence.

  doc_url: https://groups.google.com/forum/#!forum/fonttools
  dev_url: https://github.com/fonttools/fonttools

extra:
  recipe-maintainers:
    - CJ-Wright
