travis:
  secure:
    BINSTAR_TOKEN: XQJY47f2F/mn4NVbBylxlKgZ+Z+/nYlXe4Hj9XBy/e2sahc/oxg1mPoY/kumWTpLBe+euoLJSr8FhQ4sxpqH0h0Sm1VEELD7K78m7+8TRrPkTY5CLCWIuLVEKnsEQK7WussfzF/2jQ6NH8NSc0jUo8JDlLD9l6SzhwCbxPXeuB6Ee4d4en19UJB1sGQk7mNEvJlsPayYMugh5Fw6/gUme3aZ1HYGf2QxQj4mXOY8ktou5bis7tHE/kTHMYoTpdpH0mKjdBEamqNXKYn0NT4xIFBOBQhOcducvyrHlrGqKhP9lOViRKqCf8xFBOzSfZ1DtfaR4woguJVYmtQ4ROYhY2PfFe4mNyY7kKxhPt/yWeLcCZksBVYnX5aypP49ncrkcRMHx9yWaw8B4DAiS9OcHrnFgYNSWE1C9KipP4oY9zUHTgvwyNGYhGzkk28h9+47xRtWXZCB8Fsyv5XmCBzHOp52d2639AphQ4NgsP0UAiasKwOJ8dwkYF6CPo7evrDXMQ59W55NUc9XEzSxkj/xFIIXGgNsiOZZfsyEno0sO2V75okDUIvpxClkiHGJBxjUvo3J/Eki7COu7N527jvQgXZPimcvyeiX5U+kpRogZkEBUMmSaDibVgbwkRFAxSYpp0nwvbz7n5Bs7gkZSN7ifB628tHLxRz+eIXF/ZEBYeA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
